#!/bin/bash
cd $OPENSHIFT_DATA_DIR
if [ ! -d jdk1.8.0_74 ]; then
  # OpenShift currently install Java7 by default, but we require Java8
  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u74-b02/jdk-8u74-linux-i586.tar.gz
  tar -zxf jdk-8u74-linux-i586.tar.gz
fi

if [ ! -d apache-maven-3.3.9 ]; then
  wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  tar -zxf apache-maven-3.3.9-bin.tar.gz
fi

export JAVA_HOME=${OPENSHIFT_DATA_DIR}jdk1.8.0_74
export M2_HOME=${OPENSHIFT_DATA_DIR}apache-maven-3.3.9
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

# quick show of what we got
mvn -v

cd $OPENSHIFT_REPO_DIR
mvn package -s .openshift/settings.xml -Dlicense.skip=true -DskipTests=true -Dmdep.analyze.skip=true -Dduplicate-finder.skip=true -Djacoco.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
