#
# This file is part of identifier-service. It is subject to the license terms in the LICENSE file found in the top-level
# directory of this distribution and at http://creativecommons.org/publicdomain/zero/1.0/. No part of identifier-service,
# including this file, may be copied, modified, propagated, or distributed except according to the terms contained
# in the LICENSE file.
#

application:
  url: http://localhost:8080
  slack:
    message-prefix: '`%1$s` of `%2$s`:'


###############################################################################
#
# Spring configuration
#
spring:
  thymeleaf:
    cache: false
  jmx:
    enabled: false

server:
  compression:
    enabled: true # If response compression is enabled.
  display-name: id-service # Display name of the application.
